--!strict
-- Auto-generated by PSD→AI→Roblox Pipeline
-- Canvas: 1920x1080
-- Elements: 3
-- Generated: 2026-09-04T21:14:49.093Z

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local DESIGN_WIDTH = 1920
local DESIGN_HEIGHT = 1080

local GeneratedUI = {}
GeneratedUI.__index = GeneratedUI

function GeneratedUI.new()
    local self = setmetatable({}, GeneratedUI)
    self.Elements = {}
    return self
end

function GeneratedUI:CreateElement(parent, config)
    local el = Instance.new(config.Class)
    el.Name = config.Name
    el.Position = UDim2.new(
        config.X / DESIGN_WIDTH, config.OffsetX or 0,
        config.Y / DESIGN_HEIGHT, config.OffsetY or 0
    )
    el.Size = UDim2.new(
        config.Width / DESIGN_WIDTH, config.OffsetWidth or 0,
        config.Height / DESIGN_HEIGHT, config.OffsetHeight or 0
    )

    if config.BackgroundColor3 then el.BackgroundColor3 = config.BackgroundColor3 end
    if config.BackgroundTransparency ~= nil then el.BackgroundTransparency = config.BackgroundTransparency end
    if config.CornerRadius and config.CornerRadius > 0 then
        local corner = Instance.new('UICorner')
        corner.CornerRadius = UDim.new(0, config.CornerRadius)
        corner.Parent = el
    end
    if config.Text then
        el.Text = config.Text
        if config.TextSize then el.TextSize = config.TextSize end
        if config.TextColor3 then el.TextColor3 = config.TextColor3 end
        if config.Font then el.Font = config.Font end
    end
    if config.Image then
        el.Image = config.Image
        if config.ScaleType then el.ScaleType = config.ScaleType end
    end
    el.Parent = parent
    return el
end

function GeneratedUI:Build(parent)
    local screenGui = Instance.new('ScreenGui')
    screenGui.Name = 'Desktop'
    screenGui.ResetOnSpawn = false
    screenGui.IgnoreGuiInset = true
    screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
    screenGui.Parent = parent or Players.LocalPlayer:WaitForChild('PlayerGui')

    local elements = {}
    -- Background
    elements['Background'] = self:CreateElement(screenGui, {
        Class = "ImageLabel",
        Name = "Background",
        X = 0,
        Y = 0,
        Width = 1920,
        Height = 1080,
        BackgroundColor3 = Color3.fromRGB(30, 30, 46),
    })

    -- Play Button
    elements['Play_Button'] = self:CreateElement(screenGui, {
        Class = "TextButton",
        Name = "Play Button",
        X = 806,
        Y = 497,
        Width = 300,
        Height = 80,
        BackgroundColor3 = Color3.fromRGB(137, 180, 250),
        Text = "PLAY",
        TextSize = 28,
        CornerRadius = 12,
    })

    -- Settings Button
    elements['Settings_Button'] = self:CreateElement(screenGui, {
        Class = "TextButton",
        Name = "Settings Button",
        X = 858,
        Y = 622,
        Width = 200,
        Height = 60,
        BackgroundColor3 = Color3.fromRGB(166, 227, 161),
        Text = "SETTINGS",
        TextSize = 20,
        CornerRadius = 8,
    })

    self.Elements = elements
    return screenGui
end

return GeneratedUI
