-- ============================================================
-- Auto-generated by FigmaRobloxConverter (Python)
-- Figma → Roblox LuaU Export
-- ============================================================

local screenGui = Instance.new("ScreenGui")
screenGui.Name = "GeneratedUI"
screenGui.ResetOnSpawn = false
screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
screenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")

local MainMenu = Instance.new("Frame")
MainMenu.Name = "MainMenu"
MainMenu.Position = UDim2.new(0.0, 0, 0.0, 0)
MainMenu.Size = UDim2.new(1.0, 0, 1.0, 0)
MainMenu.BackgroundColor3 = Color3.fromRGB(26, 26, 46)
MainMenu.BorderSizePixel = 0
MainMenu.Parent = screenGui

  local TitleFrame = Instance.new("Frame")
  TitleFrame.Name = "TitleFrame"
  TitleFrame.Position = UDim2.new(0.5, 0, 0.1852, 0)
  TitleFrame.Size = UDim2.new(0.2083, 0, 0.0926, 0)
  TitleFrame.AnchorPoint = Vector2.new(0.5, 0.0)
  TitleFrame.BackgroundColor3 = Color3.fromRGB(22, 33, 62)
  TitleFrame.BorderSizePixel = 0
  TitleFrame.Parent = MainMenu

    local TitleText = Instance.new("TextLabel")
    TitleText.Name = "TitleText"
    TitleText.Position = UDim2.new(0.0, 0, 0.2, 0)
    TitleText.Size = UDim2.new(1.0, 0, 0.6, 0)
    TitleText.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    TitleText.BorderSizePixel = 0
    TitleText.Text = "PING PONG STRIKE"
    TitleText.TextColor3 = Color3.fromRGB(255, 255, 255)
    TitleText.TextSize = 48.0
    TitleText.TextScaled = true
    TitleText.Font = Enum.Font.GothamBold
    TitleText.TextXAlignment = Enum.TextXAlignment.Center
    TitleText.TextYAlignment = Enum.TextYAlignment.Center
    TitleText.TextWrapped = true
    TitleText.Parent = TitleFrame

  local ButtonsContainer = Instance.new("TextButton")
  ButtonsContainer.Name = "ButtonsContainer"
  ButtonsContainer.Position = UDim2.new(0.5, 0, 0.3704, 0)
  ButtonsContainer.Size = UDim2.new(0.1042, 0, 0.2222, 0)
  ButtonsContainer.AnchorPoint = Vector2.new(0.5, 0.0)
  ButtonsContainer.BackgroundTransparency = 1.0
  ButtonsContainer.BorderSizePixel = 0
  ButtonsContainer.Parent = MainMenu

    local Play_Button = Instance.new("TextButton")
    Play_Button.Name = "Play_Button"
    Play_Button.Position = UDim2.new(0.0, 0, 0.0, 0)
    Play_Button.Size = UDim2.new(1.0, 0, 0.25, 0)
    Play_Button.BackgroundColor3 = Color3.fromRGB(15, 52, 96)
    Play_Button.BorderSizePixel = 0
    Play_Button.Parent = ButtonsContainer

    local PlayButtonText = Instance.new("TextButton")
    PlayButtonText.Name = "PlayButtonText"
    PlayButtonText.Position = UDim2.new(0.0, 0, 0.0417, 0)
    PlayButtonText.Size = UDim2.new(1.0, 0, 0.1667, 0)
    PlayButtonText.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    PlayButtonText.BorderSizePixel = 0
    PlayButtonText.Text = "PLAY"
    PlayButtonText.TextColor3 = Color3.fromRGB(255, 255, 255)
    PlayButtonText.TextSize = 28.0
    PlayButtonText.TextScaled = true
    PlayButtonText.Font = Enum.Font.GothamBold
    PlayButtonText.TextXAlignment = Enum.TextXAlignment.Center
    PlayButtonText.TextYAlignment = Enum.TextYAlignment.Center
    PlayButtonText.TextWrapped = true
    PlayButtonText.Parent = ButtonsContainer

    local Settings_Button = Instance.new("TextButton")
    Settings_Button.Name = "Settings_Button"
    Settings_Button.Position = UDim2.new(0.0, 0, 0.25, 0)
    Settings_Button.Size = UDim2.new(1.0, 0, 0.25, 0)
    Settings_Button.BackgroundColor3 = Color3.fromRGB(15, 52, 96)
    Settings_Button.BorderSizePixel = 0
    Settings_Button.Parent = ButtonsContainer

    local SettingsButtonText = Instance.new("TextButton")
    SettingsButtonText.Name = "SettingsButtonText"
    SettingsButtonText.Position = UDim2.new(0.0, 0, 0.2917, 0)
    SettingsButtonText.Size = UDim2.new(1.0, 0, 0.1667, 0)
    SettingsButtonText.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    SettingsButtonText.BorderSizePixel = 0
    SettingsButtonText.Text = "SETTINGS"
    SettingsButtonText.TextColor3 = Color3.fromRGB(255, 255, 255)
    SettingsButtonText.TextSize = 28.0
    SettingsButtonText.TextScaled = true
    SettingsButtonText.Font = Enum.Font.GothamBold
    SettingsButtonText.TextXAlignment = Enum.TextXAlignment.Center
    SettingsButtonText.TextYAlignment = Enum.TextYAlignment.Center
    SettingsButtonText.TextWrapped = true
    SettingsButtonText.Parent = ButtonsContainer

    local Shop_Button = Instance.new("TextButton")
    Shop_Button.Name = "Shop_Button"
    Shop_Button.Position = UDim2.new(0.0, 0, 0.5, 0)
    Shop_Button.Size = UDim2.new(1.0, 0, 0.25, 0)
    Shop_Button.BackgroundColor3 = Color3.fromRGB(15, 52, 96)
    Shop_Button.BorderSizePixel = 0
    Shop_Button.Parent = ButtonsContainer

    local ShopButtonText = Instance.new("TextButton")
    ShopButtonText.Name = "ShopButtonText"
    ShopButtonText.Position = UDim2.new(0.0, 0, 0.5417, 0)
    ShopButtonText.Size = UDim2.new(1.0, 0, 0.1667, 0)
    ShopButtonText.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    ShopButtonText.BorderSizePixel = 0
    ShopButtonText.Text = "SHOP"
    ShopButtonText.TextColor3 = Color3.fromRGB(255, 255, 255)
    ShopButtonText.TextSize = 28.0
    ShopButtonText.TextScaled = true
    ShopButtonText.Font = Enum.Font.GothamBold
    ShopButtonText.TextXAlignment = Enum.TextXAlignment.Center
    ShopButtonText.TextYAlignment = Enum.TextYAlignment.Center
    ShopButtonText.TextWrapped = true
    ShopButtonText.Parent = ButtonsContainer

  local Footer = Instance.new("Frame")
  Footer.Name = "Footer"
  Footer.Position = UDim2.new(0.0, 0, 0.9074, 0)
  Footer.Size = UDim2.new(1.0, 0, 0.0926, 0)
  Footer.BackgroundColor3 = Color3.fromRGB(15, 52, 96)
  Footer.BorderSizePixel = 0
  Footer.Parent = MainMenu
